"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect } from 'react';
import Navbar from './components/navbar/page';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(()=>{
    if(typeof window!== undefined){
      require('bootstrap/dist/js/bootstrap.bundle')
    }
  }, [])
  return (
    <div>
      <Navbar/>
      <main >{children}</main>
    </div>
  )
}
